CFLAGS=-DPS2GXEMU
TARGET=ps2gxemu_stage1_file
SRC_SELF=../ps2emu_gen453/ps2_gxemu.self
OUT_SELF=ps2_gxemu.self
TEXT_OFFSET=0x10000
PAYLOAD_ADDR=0x8CAD8
SH_ADDR=0x2087A0
DATA_ADDR=0x677880
PATCH_ADDR=0
PATCH_DATA=0

include Makefile.common


#../ps2emu_gen446/ps2emu_gen ps2gxemu_stage1_file.bin ../ps2emu_gen453/ps2_gxemu.self ps2_gxemu.self 0x10000 0x8CAD8 0x2087A0 0x677880 0 0
make: ../ps2emu_gen446/ps2emu_gen: Command not found
