CFLAGS=-DPS2HWEMU
TARGET=ps2hwemu_stage1_file
SRC_SELF=../ps2emu_gen453/ps2_emu.self
OUT_SELF=ps2_emu.self
TEXT_OFFSET=0x10000
PAYLOAD_ADDR=0x23CEC
SH_ADDR=0x1BFEC8
DATA_ADDR=0x4f7930
PATCH_ADDR=0xFFFFFFFF
PATCH_DATA=0x00000000

include Makefile.common

#../ps2emu_gen446/ps2emu_gen ps2hwemu_stage1_file.bin ../ps2emu_gen453/ps2_emu.self ps2_emu.self 0x10000 0x23CEC 0x1BFEC8 0x4f7930 0xFFFFFFFF 0x00000000
